[package]
name = "functions_without_ownership"
version = "0.1.0"
authors = ["alschofield93 <alschofield93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
